// <auto-generated />
using System;
using Gestion_Bibliotheque_Livre.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Bibliotheque_Livre.Migrations
{
    [DbContext(typeof(DbContextBibliotheque))]
    [Migration("20251112202054_CreationDB")]
    partial class CreationDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliothequeApp.Models.Auteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Roman"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Science-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Fantastique"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Policier"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Biographie"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Histoire"
                        });
                });

            modelBuilder.Entity("BibliothequeApp.Models.DetailsLivre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("NombrePages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LivreId")
                        .IsUnique();

                    b.ToTable("DetailsLivres");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.ToTable("Livres");
                });

            modelBuilder.Entity("BibliothequeApp.Models.LivreCategorie", b =>
                {
                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.HasKey("LivreId", "CategorieId");

                    b.HasIndex("CategorieId");

                    b.ToTable("LivreCategories");
                });

            modelBuilder.Entity("BibliothequeApp.Models.DetailsLivre", b =>
                {
                    b.HasOne("BibliothequeApp.Models.Livre", "Livre")
                        .WithOne("Details")
                        .HasForeignKey("BibliothequeApp.Models.DetailsLivre", "LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Livre", b =>
                {
                    b.HasOne("BibliothequeApp.Models.Auteur", "Auteur")
                        .WithMany("Livres")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");
                });

            modelBuilder.Entity("BibliothequeApp.Models.LivreCategorie", b =>
                {
                    b.HasOne("BibliothequeApp.Models.Categorie", "Categorie")
                        .WithMany("LivreCategories")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliothequeApp.Models.Livre", "Livre")
                        .WithMany("LivreCategories")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Auteur", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Categorie", b =>
                {
                    b.Navigation("LivreCategories");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Livre", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("LivreCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
