//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Bibliotheque_Livre.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gestion_Bibliotheque_Livre.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authors.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author Management.
        /// </summary>
        public static string AuthorManagement {
            get {
                return ResourceManager.GetString("AuthorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authors.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authors Count.
        /// </summary>
        public static string AuthorsCount {
            get {
                return ResourceManager.GetString("AuthorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author with most books.
        /// </summary>
        public static string AuthorWithMostbooks {
            get {
                return ResourceManager.GetString("AuthorWithMostbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book Management.
        /// </summary>
        public static string BookManagement {
            get {
                return ResourceManager.GetString("BookManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Books Count.
        /// </summary>
        public static string BooksCount {
            get {
                return ResourceManager.GetString("BooksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book Title.
        /// </summary>
        public static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Categories Count.
        /// </summary>
        public static string CategoriesCount {
            get {
                return ResourceManager.GetString("CategoriesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category Management.
        /// </summary>
        public static string CategoryManagement {
            get {
                return ResourceManager.GetString("CategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copies.
        /// </summary>
        public static string Copies {
            get {
                return ResourceManager.GetString("Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a date.
        /// </summary>
        public static string DatePicker_Placeholder {
            get {
                return ResourceManager.GetString("DatePicker_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select an author..
        /// </summary>
        public static string ErrorAuthorRequired {
            get {
                return ResourceManager.GetString("ErrorAuthorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This book already exists..
        /// </summary>
        public static string ErrorBookExists {
            get {
                return ResourceManager.GetString("ErrorBookExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book title is required..
        /// </summary>
        public static string ErrorBookTitle {
            get {
                return ResourceManager.GetString("ErrorBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a category..
        /// </summary>
        public static string ErrorCategoryRequired {
            get {
                return ResourceManager.GetString("ErrorCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of copies must be zero or a positive number..
        /// </summary>
        public static string ErrorCopiesInvalid {
            get {
                return ResourceManager.GetString("ErrorCopiesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication date is required..
        /// </summary>
        public static string ErrorDateRequired {
            get {
                return ResourceManager.GetString("ErrorDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISBN is required..
        /// </summary>
        public static string ErrorISBNRequired {
            get {
                return ResourceManager.GetString("ErrorISBNRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of pages must be a positive number..
        /// </summary>
        public static string ErrorPagesInvalid {
            get {
                return ResourceManager.GetString("ErrorPagesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occurred.
        /// </summary>
        public static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discover and manage your literary treasure with ease. Your digital library gives you instant access to your entire collection..
        /// </summary>
        public static string ExploreDescription {
            get {
                return ResourceManager.GetString("ExploreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explore your collection.
        /// </summary>
        public static string ExploreTitle {
            get {
                return ResourceManager.GetString("ExploreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access all your books with one click.
        /// </summary>
        public static string Feature1Description {
            get {
                return ResourceManager.GetString("Feature1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete Collection.
        /// </summary>
        public static string Feature1Title {
            get {
                return ResourceManager.GetString("Feature1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Easily find your favorite writers.
        /// </summary>
        public static string Feature2Description {
            get {
                return ResourceManager.GetString("Feature2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organized Authors.
        /// </summary>
        public static string Feature2Title {
            get {
                return ResourceManager.GetString("Feature2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classify your books by genre and theme.
        /// </summary>
        public static string Feature3Description {
            get {
                return ResourceManager.GetString("Feature3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Smart Categories.
        /// </summary>
        public static string Feature3Title {
            get {
                return ResourceManager.GetString("Feature3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  General Information.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home Page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISBN.
        /// </summary>
        public static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EN English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last book added.
        /// </summary>
        public static string LastBookAdded {
            get {
                return ResourceManager.GetString("LastBookAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Library Management System.
        /// </summary>
        public static string LibraryManagementSystem {
            get {
                return ResourceManager.GetString("LibraryManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Library statistics and insights.
        /// </summary>
        public static string LibraryStat {
            get {
                return ResourceManager.GetString("LibraryStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Library Statistics.
        /// </summary>
        public static string LibraryStatistics {
            get {
                return ResourceManager.GetString("LibraryStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage authors and their information.
        /// </summary>
        public static string ManageAuthInfo {
            get {
                return ResourceManager.GetString("ManageAuthInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage Authors.
        /// </summary>
        public static string ManageAuthors {
            get {
                return ResourceManager.GetString("ManageAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage book categories.
        /// </summary>
        public static string ManageBookCategorie {
            get {
                return ResourceManager.GetString("ManageBookCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage books and their details.
        /// </summary>
        public static string ManageBookDetails {
            get {
                return ResourceManager.GetString("ManageBookDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage Books.
        /// </summary>
        public static string ManageBooks {
            get {
                return ResourceManager.GetString("ManageBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage Categories.
        /// </summary>
        public static string ManageCategories {
            get {
                return ResourceManager.GetString("ManageCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Most popular category.
        /// </summary>
        public static string MostPopularCategory {
            get {
                return ResourceManager.GetString("MostPopularCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NAVIGATION.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use the navigation menu on the left side to explore the different sections of your library: Authors, Books, Categories and Statistics..
        /// </summary>
        public static string NavigationDescription {
            get {
                return ResourceManager.GetString("NavigationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How to navigate?.
        /// </summary>
        public static string NavigationTitle {
            get {
                return ResourceManager.GetString("NavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of authors.
        /// </summary>
        public static string NumberOfAuthors {
            get {
                return ResourceManager.GetString("NumberOfAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of books.
        /// </summary>
        public static string NumberOfBooks {
            get {
                return ResourceManager.GetString("NumberOfBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number Of Categories.
        /// </summary>
        public static string NumberOfCategories {
            get {
                return ResourceManager.GetString("NumberOfCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of Copies.
        /// </summary>
        public static string NumberOfCopies {
            get {
                return ResourceManager.GetString("NumberOfCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of pages.
        /// </summary>
        public static string NumberOfPages {
            get {
                return ResourceManager.GetString("NumberOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pages Count.
        /// </summary>
        public static string PagesCount {
            get {
                return ResourceManager.GetString("PagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication date.
        /// </summary>
        public static string PublicationDate {
            get {
                return ResourceManager.GetString("PublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quick Stats.
        /// </summary>
        public static string QuickStats {
            get {
                return ResourceManager.GetString("QuickStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marcel Proust.
        /// </summary>
        public static string QuoteAuthor {
            get {
                return ResourceManager.GetString("QuoteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading is a friendship.
        /// </summary>
        public static string QuoteText {
            get {
                return ResourceManager.GetString("QuoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select an author....
        /// </summary>
        public static string SelectAuthor {
            get {
                return ResourceManager.GetString("SelectAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a category....
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your library is ready to be explored.
        /// </summary>
        public static string StatusMessage {
            get {
                return ResourceManager.GetString("StatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book added successfully!.
        /// </summary>
        public static string SuccessBookAdded {
            get {
                return ResourceManager.GetString("SuccessBookAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Library Management.
        /// </summary>
        public static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View Statistics.
        /// </summary>
        public static string ViewStatistics {
            get {
                return ResourceManager.GetString("ViewStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your literary management portal.
        /// </summary>
        public static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to your Library.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
